name = "Raphina-AI/raphina-cardano"
version = "0.0.0"
license  = "Apache-2.0"
description = "Aiken contracts for project 'aiken-tutorial/hello-world'"
 
[repository]
user = 'Raphina-AI'
project = 'raphina-cardano'
platform = 'github'
 
[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"
 